# Generated by Django 6.0.6 on 2026-07-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('store', '0009_alter_cart_user_alter_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
