# Generated by Django 6.0.6 on 2026-07-03 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Vendor',
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='author',
            new_name='vendor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='order',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slider',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
        ),
    ]
