# Generated by Django 6.0.6 on 2026-07-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderreport',
            options={'verbose_name_plural': 'Order'},
        ),
    ]
