# Generated by Django 5.2.14 on 2026-05-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_author_alter_tag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='birth_day',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(null=True),
        ),
    ]
