# Generated by Django 5.2.14 on 2026-05-20 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_remove_article_author_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='django_app.tag'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_app.author'),
        ),
    ]
